# Generated by Django 4.0.3 on 2022-03-04 03:23

from django.db import migrations, models
import spotify.models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.FileField(null=True, upload_to=spotify.models.lyrics_path),
        ),
    ]
