# Generated by Django 4.0.3 on 2022-03-04 08:16

from django.db import migrations, models
import spotify.models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_song_times_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to=spotify.models.audio_path),
        ),
    ]
