# Generated by Django 4.0.3 on 2022-03-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
