# Generated by Django 4.0.3 on 2022-03-06 10:02

from django.db import migrations, models
import spotify.models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(null=True, upload_to=spotify.models.audio_path),
        ),
    ]
