# Generated by Django 3.2.12 on 2022-03-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='times_plaplyed',
            new_name='times_played',
        ),
    ]
