# Generated by Django 3.2.12 on 2022-03-07 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0002_rename_times_plaplyed_song_times_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeORDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('0', 'Like'), ('1', 'Dislike')], default='1', max_length=3)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.FileField(null=True, upload_to='song/lyrics/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(null=True, upload_to='song/audio/'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='likeordislike',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_song', to='songs.song'),
        ),
    ]
