# Generated by Django 4.0 on 2022-01-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_question_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='question_pics'),
        ),
    ]
