# Generated by Django 4.0 on 2022-01-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
