# Generated by Django 4.0 on 2022-03-01 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0011_remove_answer_accepted_remove_answer_votes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Task',
        ),
    ]
