# Generated by Django 4.0 on 2022-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_rename_question_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='question',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='question_image',
        ),
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_pics'),
        ),
    ]
