# Generated by Django 4.0 on 2022-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_rename_question_answer_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
