# Generated by Django 4.0 on 2022-03-01 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_delete_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='likes',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
